project:
  type: website
  output-dir: docs

format:
  revealjs:
    theme: solarized
    slide-number: true
    monofont: "Liberation Mono"
  beamer:
    includes-in-header: preamble.tex
    monofont: "Liberation Mono"
  pptx:
    monofont: "Liberation Mono"
